name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: nix develop -c ruff check src/ tests/

      - name: Test
        run: nix develop -c just test
